// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Test = require("./test");

function http_req(prim, prim$1) {
  return Test.http_req(prim, prim$1);
}

function js_callback(msg) {
  console.log("RETURN from the callback");
  console.log(msg);
  return /* () */0;
}

function req(url) {
  Test.http_req(url, js_callback);
  return /* () */0;
}

function reducer_fun(state, action) {
  if (action.tag) {
    return /* record */[/* url : record */[
              /* hostname */state[/* url */0][/* hostname */0],
              /* page */action[0]
            ]];
  } else {
    return /* record */[/* url : record */[
              /* hostname */action[0],
              /* page */state[/* url */0][/* page */1]
            ]];
  }
}

function Component(Props) {
  var match = React.useReducer(reducer_fun, /* record */[/* url : record */[
          /* hostname */"http://ec2-34-246-176-2.eu-west-1.compute.amazonaws.com:3000",
          /* page */"/test"
        ]]);
  var dispatch = match[1];
  var st = match[0];
  var match$1 = React.useState((function () {
          return st[/* url */0][/* hostname */0] + st[/* url */0][/* page */1];
        }));
  var handleClick = function (_event) {
    var r = st[/* url */0][/* hostname */0] + st[/* url */0][/* page */1];
    console.log("REQUESTING: " + r);
    return req(r);
  };
  return React.createElement("div", {
              className: "app"
            }, React.createElement("p", undefined, "Requested hostname: " + st[/* url */0][/* hostname */0]), React.createElement("input", {
                  placeholder: "Write something to do",
                  size: 90,
                  type: "text",
                  value: st[/* url */0][/* hostname */0],
                  onKeyDown: (function (evt) {
                      return /* () */0;
                    }),
                  onChange: (function (evt) {
                      return Curry._1(dispatch, /* SetHostname */Block.__(0, [evt.target.value]));
                    })
                }), React.createElement("p", undefined, "Requested page: " + st[/* url */0][/* page */1]), React.createElement("input", {
                  placeholder: "Write something to do",
                  type: "text",
                  value: st[/* url */0][/* page */1],
                  onKeyDown: (function (evt) {
                      return /* () */0;
                    }),
                  onChange: (function (evt) {
                      return Curry._1(dispatch, /* SetPage */Block.__(1, [evt.target.value]));
                    })
                }), React.createElement("p", undefined, "Requested URL is: " + match$1[0]), React.createElement("button", {
                  onClick: handleClick
                }, "HTTP Request"));
}

var make = Component;

exports.http_req = http_req;
exports.js_callback = js_callback;
exports.req = req;
exports.reducer_fun = reducer_fun;
exports.make = make;
/* react Not a pure module */
