// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component$ReactHooksTemplate = require("./Component.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component$ReactHooksTemplate.make, { }), "index");

/*  Not a pure module */
